FROM node:18-alpine
WORKDIR /app
COPY ../../package*.json ./
COPY ../../packages ./packages
COPY ../../apps/api ./apps/api
RUN npm ci --omit=dev --workspace @breakeven/api --workspace @breakeven/shared
WORKDIR /app/apps/api
CMD ["node", "dist/index.js"]
